/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.customermanagementsystem;

import javax.swing.JButton;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author coolm
 */

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form CustomerManagementFrame
     */
    
    // [ DARK/LIGHT MODE STUFF ]
    
    // [ VARIABLES THAT CAN BE USED GLOBALLY ]
    
    final static Color darkColor = new Color(51,51,51);
    final static Color lightColor = new Color(255,255,255);
    
    public void updateThemeAppearance() {
        // [ TABLE OF BUTTONS THAT WILL CHANGE COLOR ]
        JButton[] buttons = new JButton[]{CustomersButton, ActorsButton, ReportsButton, ExitButton};
        
        boolean darkMode = CustomerManagementSystem.darkMode;
        
        // [ JOPTIONPANE ]
        UIManager.put("OptionPane.background", darkMode ? darkColor : lightColor);
        UIManager.put("Panel.background", darkMode ? darkColor : lightColor);
        UIManager.put("OptionPane.messageForeground", darkMode ? lightColor : darkColor.darker());
        UIManager.put("Button.background", darkMode ? darkColor.darker() : lightColor.darker());
        UIManager.put("Button.foreground", darkMode ? lightColor : darkColor.darker());
        
        if (darkMode) {
            // [ SET ITEMS TO DARK ]
            // [ JOPTIONPANE ]
        
            DarkModeToggle.setText("Dark Mode: ON");
            DarkModeToggle.setBackground(darkColor.darker());
            DarkModeToggle.setForeground(lightColor);
            
            // Background Color
            getContentPane().setBackground(darkColor);
            
            // Title Color
            Title.setForeground(lightColor);
            
            for (JButton btn : buttons) {
                btn.setBackground(darkColor.darker());
                btn.setForeground(lightColor);
            }
            
        } else {
            // [ SET ITEMS TO LIGHT ]
            
            DarkModeToggle.setText("Dark Mode: OFF");
            DarkModeToggle.setBackground(lightColor.darker());
            DarkModeToggle.setForeground(darkColor);
            
            // Background Color
            getContentPane().setBackground(lightColor);
            
            // Title Color
            Title.setForeground(darkColor);
            
            for (JButton btn : buttons) {
                btn.setBackground(lightColor.darker());
                btn.setForeground(darkColor);
            }
        }
        
    }
    
    public MainMenu() {
        initComponents();
        
        // [ SETS TOGGLE TO WHATEVER THE DARK MODE VARIABLE IS - WHEN MAIN MENU IS CREATED ]
        DarkModeToggle.setSelected(CustomerManagementSystem.darkMode);
        
        updateThemeAppearance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomersButton = new javax.swing.JButton();
        ActorsButton = new javax.swing.JButton();
        ReportsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        DarkModeToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CustomersButton.setBackground(new java.awt.Color(51, 51, 51));
        CustomersButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustomersButton.setForeground(new java.awt.Color(255, 255, 255));
        CustomersButton.setText(" CUSTOMERS");
        CustomersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CustomersButton.setFocusPainted(false);
        CustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersButtonActionPerformed(evt);
            }
        });

        ActorsButton.setBackground(new java.awt.Color(51, 51, 51));
        ActorsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ActorsButton.setForeground(new java.awt.Color(255, 255, 255));
        ActorsButton.setText(" ACTORS");
        ActorsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ActorsButton.setFocusPainted(false);
        ActorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActorsButtonActionPerformed(evt);
            }
        });

        ReportsButton.setBackground(new java.awt.Color(51, 51, 51));
        ReportsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportsButton.setText("REPORTS");
        ReportsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReportsButton.setFocusPainted(false);
        ReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(51, 51, 51));
        ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("EXIT");
        ExitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitButton.setFocusPainted(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("MANAGEMENT MENU");
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DarkModeToggle.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        DarkModeToggle.setText("Dark Mode: OFF");
        DarkModeToggle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DarkModeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarkModeToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DarkModeToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DarkModeToggle)
                .addGap(22, 22, 22)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(CustomersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersButtonActionPerformed
        // TODO add your handling code here:
        
        // OPEN CUSTOMER DATA TABLE
        new CustomerManagementForm().setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_CustomersButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ActorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActorsButtonActionPerformed
        // TODO add your handling code here:
        
        new ActorManagementForm().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_ActorsButtonActionPerformed

    private void ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtonActionPerformed
        // TODO add your handling code here:
        
        new ReportForm().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_ReportsButtonActionPerformed

    private void DarkModeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarkModeToggleActionPerformed
        // [ UPDATE GLOBAL DARK MODE VARIABLE WHENEVER TOGGLED ]
        CustomerManagementSystem.darkMode = DarkModeToggle.isSelected();
        updateThemeAppearance();
    }//GEN-LAST:event_DarkModeToggleActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActorsButton;
    private javax.swing.JButton CustomersButton;
    private javax.swing.JToggleButton DarkModeToggle;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ReportsButton;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
